set -g mode-keys vi
bind-key y set-window-option synchronize-panes
# prefix + Shift + Arrow resize
bind -r S-Left  resize-pane -L 2
bind -r S-Right resize-pane -R 2
bind -r S-Up    resize-pane -U 2
bind -r S-Down  resize-pane -D 2

set-option -g default-terminal "xterm-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g status-position bottom
set -g status-justify left
set -sg escape-time 0

# --- Tokyo Night Theme Parameters ---
set -g mode-style "fg=#7aa2f7,bg=#3b4261"

set -g message-style "fg=#7aa2f7,bg=#3b4261"
set -g message-command-style "fg=#7aa2f7,bg=#3b4261"

set -g pane-border-style "fg=#3b4261"
set -g pane-active-border-style "fg=#7aa2f7"

set -g status-style "fg=#7aa2f7,bg=#1f2335"

set -g status-left "#[fg=#15161e,bg=#7aa2f7,bold] #S "
set -g status-right "#[fg=#7aa2f7,bg=#3b4261] %Y-%m-%d %I:%M %p "

setw -g window-status-activity-style "underscore,fg=#a9b1d6,bg=#1f2335"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#a9b1d6,bg=#1f2335"
setw -g window-status-format " #I #W #F "
setw -g window-status-current-format "#[fg=#7aa2f7,bg=#3b4261,bold] #I #W #F "
